version: '3.7'

networks:
  qa-automation:

services:

  # PHP Service
  php:
    image: ${APP_BASE}/php
    build:
      dockerfile: dockerfile
      context: ${PWD}/stack/php   
      args:
        WORKDIR: ${APP_WORKING_DIR}
    container_name: php
    env_file:
      - .env
    volumes:
      - ./app:${APP_WORKING_DIR}:delegated
      - ${PWD}/stack/php/conf/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ${PWD}/stack/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - qa-automation

  # The Selenium Standalone Chrome
  selenium-chrome:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    shm_size: '2gb'
    ports:
      - 4444:4444
    networks:
      - qa-automation

  # The Selenium Standalone Firefox
  selenium-firefox:
    image: selenium/standalone-firefox
    container_name: selenium-firefox
    shm_size: '2gb'
    #volumes:
    #  - ./selenium/shm:/dev/shm
    ports:
      - 4445:4444
    networks:
      - qa-automation