version: '3.7'

networks:
  end-to-end:

services:    
  # PHP Service
  php:
    image: ${APP_BASE}/php
    build:
      dockerfile: dockerfile
      context: ${PWD}/stack/php   
      args:
        WORKDIR: ${APP_WORKING_DIR}
    container_name: php
    volumes:
      - ./app:${APP_WORKING_DIR}:delegated
      - ${PWD}/stack/php/conf/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ${PWD}/stack/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - end-to-end

  # PHP Artisan Service
  artisan:
    image: ${APP_BASE}/artisan:latest
    build:
      dockerfile: dockerfile
      context: ${PWD}/stack/php
      args:
        WORKDIR: ${APP_WORKING_DIR}  
    container_name: artisan
    volumes:
      - ./app:${APP_WORKING_DIR}:delegated
    working_dir: ${APP_WORKING_DIR}
    user: ${APP_USER}
    entrypoint: ['php', '${APP_WORKING_DIR}/artisan']
    networks:
      - end-to-end

  # Composer Service
  composer:
    build:
      dockerfile: dockerfile
      context: ${PWD}/stack/composer    
    container_name: composer
    volumes:
      - ./app:${APP_WORKING_DIR}
    working_dir: ${APP_WORKING_DIR}
    depends_on:
      - php
    networks:
      - end-to-end
    entrypoint: ['composer', '--ignore-platform-reqs']

  # The Selenium Server
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - 4444:4444
    networks:
      - end-to-end