FROM php:7.4-fpm-alpine

# Build Time Arguments
ARG XDEBUG_VERSION=2.9.8
ARG WORKDIR=/var/www/html

# Setup dependencies
RUN apk update && apk add --no-cache \
    bash \
    icu-dev \
    libzip-dev \
    shadow \
    zlib-dev \
    freetype \
    freetype-dev \
    libpng \
    libpng-dev \
    libjpeg-turbo \
    libxml2-dev \
    libjpeg-turbo-dev g++ make autoconf

# Installing Imagemagick
RUN set -ex \
    && apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS imagemagick-dev libtool \
    && export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" \
    && pecl install imagick-3.4.3 \
    && docker-php-ext-enable imagick \
    && apk add --no-cache --virtual .imagick-runtime-deps imagemagick \
    && apk del .phpize-deps

# Install PHP Extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
    bcmath \
    gd \
    zip \
    && apk del --no-cache freetype freetype-dev libpng libpng-dev libjpeg-turbo libjpeg-turbo-dev

RUN apk add --update --no-cache \
    yaml && \
    apk add --update --no-cache --virtual .docker-php-symfony-dependancies \
    yaml-dev && \
    pecl install yaml && \
    docker-php-ext-enable yaml; \
    apk del .docker-php-symfony-dependancies && \
    php -m;

# copy the Composer PHAR from the Composer image into the PHP image
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer    

# Add PHP Configuration files
ADD ./conf/www.conf /usr/local/etc/php-fpm.d/www.conf
ADD ./conf/custom.ini /usr/local/etc/php/conf.d/custom.ini

# Creat Docker User
RUN usermod -u 1000 www-data && \
    groupmod -g 1000 www-data

# Set Utility functions and bash_profile
COPY ./scripts.sh /usr/local/bin/scripts.sh
COPY ./.bashrc /home/www-data/.bashrc

# Make Scripts and Bashrc executable
RUN chmod +x /usr/local/bin/scripts.sh && chmod +x /home/www-data/.bashrc

RUN mkdir -p $WORKDIR

RUN chown -R www-data:www-data $WORKDIR && \
    chown www-data:www-data /usr/local/etc/php/conf.d

# Change Docker User
USER www-data

WORKDIR $WORKDIR